name: Build TrollStore helper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 拉取当前仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Trollhelper  # 明确指定检出路径

      # 2. 安装依赖
      - name: Install dependencies
        run: |
          brew update
          brew install ldid xz openssl@3

      # 3. 克隆 Theos
      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos

      # 4. 克隆 SDK
      - name: Clone SDK
        run: |
          rm -rf $GITHUB_WORKSPACE/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos/sdks

      # 5. 克隆 ChOma 项目 (解决头文件缺失问题)
      - name: Clone ChOma
        run: |
          git clone https://github.com/opa334/ChOma.git $GITHUB_WORKSPACE/ChOma

      # 6. 指向最新 Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # 7. 设置环境变量 (解决openssl路径问题)
      - name: Setup environment
        run: |
          echo "OPENSSL_PREFIX=$(brew --prefix openssl@3)" >> $GITHUB_ENV

      # 8. 修复构建步骤
      - name: Build
        run: |
          # 进入项目目录
          cd $GITHUB_WORKSPACE/Trollhelper
          
          # 修复 fastPathSign 的构建路径
          cd Exploits/fastPathSign
          make OPENSSL_INCLUDE="-I${{ env.OPENSSL_PREFIX }}/include" CHOMA_INCLUDE="-I$GITHUB_WORKSPACE/ChOma/src"
          cd ../..
          
          # 修复文件复制路径
          cp Exploits/fastPathSign/fastPathSign Exploits/fastPathSign/fastPathSign
          
          # 构建主项目
          make clean
          make package
        env:
          THEOS: $GITHUB_WORKSPACE/theos

      # 9. 上传产物
      - name: Upload helper
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore
          path: Trollhelper/packages/*
