name: Build TrollStore IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 拉取当前仓库
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装依赖
      - name: Install dependencies
        run: |
          brew update || true
          brew install ldid xz

      # 3. 克隆 Theos 到固定目录
      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos

      # 4. 克隆 SDK
      - name: Clone SDK
        run: |
          rm -rf $GITHUB_WORKSPACE/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos/sdks

      # 5. 指向最新 Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # 6. 构建
      - name: Build
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          cd Trollhelper
          make clean
          make package

      # 7. 上传产物
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore
          path: packages/*
