name: Build TrollStore IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest   # 必须 macOS 才能用 Xcode

    steps:
      # 1. 拉取 TrollStore 源码
      - name: Checkout TrollStore
        uses: actions/checkout@v4
        with:
          repository: opa334/TrollStore
          path: trollstore

      # 2. 安装 Theos（使用正确的 action）
      - name: Install Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: theos
          orion: 'false'

      # 3. 选择最新版 Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # 4. 构建
      - name: Build
        working-directory: trollstore
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make clean
          make package

      # 5. 上传产物
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore
          path: trollstore/packages/*
