name: Build TrollStore helper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 拉取当前仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Trollhelper

      # 2. 安装依赖
      - name: Install dependencies
        run: |
          brew update
          brew install ldid xz openssl@3

      # 3. 克隆 Theos
      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos

      # 4. 克隆 SDK
      - name: Clone SDK
        run: |
          rm -rf $GITHUB_WORKSPACE/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos/sdks

      # 5. 指向最新 Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # 6. 设置环境变量
      - name: Setup environment
        run: |
          echo "OPENSSL_PREFIX=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV

      # 7. 修复构建步骤
      - name: Build
        run: |
          # 进入项目目录
          cd $GITHUB_WORKSPACE/Trollhelper
          
          # 进入 fastPathSign 目录
          cd Exploits/fastPathSign
          
          # 下载缺失的头文件到 src 目录
          curl -o src/FAT.h https://raw.githubusercontent.com/opa334/ChOma/main/src/FAT.h
          curl -o src/CSBlob.h https://raw.githubusercontent.com/opa334/ChOma/main/src/CSBlob.h
          
          # 构建 fastPathSign
          clang -framework Foundation -framework CoreServices -framework Security \
                -fobjc-arc \
                -I${{ env.OPENSSL_PREFIX }}/include \
                -o fastPathSign \
                src/codesign.m src/main.m src/coretrust_bug.c \
                -L${{ env.OPENSSL_PREFIX }}/lib -lcrypto
          
          # 返回项目根目录
          cd $GITHUB_WORKSPACE/Trollhelper
          
          # 构建主项目
          make clean
          make package

      # 8. 上传产物
      - name: Upload helper
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore
          path: Trollhelper/packages/*
