name: Build TrollStore helper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
          # 0. 自动下载 fastPathSign 并提交到仓库
      - name: Download & commit fastPathSign
        run: |
          mkdir -p Exploits/fastPathSign
          curl -L https://github.com/opa334/TrollStore/releases/download/2.0.15/fastPathSign \
               -o Exploits/fastPathSign/fastPathSign
          chmod +x Exploits/fastPathSign/fastPathSign
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Exploits/fastPathSign/fastPathSign
          git diff --cached --quiet || git commit -m "CI: add fastPathSign binary"
          git push

      # 1. 拉取当前仓库
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装依赖
      - name: Install dependencies
        run: |
          brew update || true
          brew install ldid xz

      # 3. 克隆 Theos
      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos

      # 4. 克隆 SDK
      - name: Clone SDK
        run: |
          rm -rf $GITHUB_WORKSPACE/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos/sdks

      # 5. 指向最新 Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # 6. 构建
      - name: Build
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          cd Trollhelper
          make clean
          make package

      # 7. 上传产物
      - name: Upload helper
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore
          path: Trollhelper/packages/*
