name: Build TrollStore IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest   # 必须 macOS

    steps:
      # 1. 拉取 TrollStore 源码
      - name: Checkout TrollStore
        uses: actions/checkout@v4
        with:
          repository: opa334/TrollStore
          path: trollstore

      # 2. 手动拉取 Theos
      - name: Clone Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
Troubleshooting
      # 4. 选择最新版 Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # 5. 构建
      - name: Build
        working-directory: trollstore
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          make clean
          make package

      # 6. 上传产物
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore
          path: trollstore/packages/*
