name: Build TrollStore and List Artifacts

on:
  workflow_dispatch: # 只允许手动触发

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Xcode
        uses: actions/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Install dependencies
        run: |
          brew install ldid dpkg
          # 安装 pwnify
          if [ -d "Pwnify" ]; then
            cd Pwnify
            make
            sudo cp pwnify /usr/local/bin/
            cd ..
          fi

      - name: Build TrollStore
        run: |
          make all
          
      - name: List all build artifacts
        run: |
          echo "构建完成，_build 目录内容如下:"
          echo "=========================================="
          find ./_build -type f -o -type d | sort
          echo ""
          echo "文件详情:"
          echo "=========================================="
          find ./_build -type f -exec ls -la {} \;
          echo ""
          echo "文件大小统计:"
          echo "=========================================="
          find ./_build -type f -exec du -h {} \; | sort -hr

      - name: Upload all build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TrollStore-Complete-Build
          path: ./_build/
          if-no-files-found: error
